package com.spoiledmilk.spritebaker;

import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/** Runnable desktop entry point. CLI entry points remain Main and SelectorMain. */
public final class DesktopMain {
    private DesktopMain(){}
    public static void main(String[] args){if(GraphicsEnvironment.isHeadless()){System.err.println("RSC Sprite Baker desktop requires a graphical environment. CLI entry points remain available.");System.exit(2);}SwingUtilities.invokeLater(()->{try{UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}catch(Exception ignored){}showWelcome(null);});}
    static void showWelcome(Component owner){DesktopPreferences preferences=DesktopPreferences.load(DesktopPreferences.defaultFile());String[] choices=preferences.recentProjects.isEmpty()?new String[]{"Create New Project","Open Project","Cancel"}:new String[]{"Open Recent Project","Create New Project","Open Other Project","Cancel"};int selected=JOptionPane.showOptionDialog(owner,"Choose how to begin. Cache and export folders remain machine-local; the project file stays portable.","Welcome to RSC Sprite Baker",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null,choices,choices[0]);if(selected<0||"Cancel".equals(choices[selected]))return;if("Open Recent Project".equals(choices[selected])){DesktopPreferences.RecentProject recent=(DesktopPreferences.RecentProject)JOptionPane.showInputDialog(owner,"Recent projects","Open Recent",JOptionPane.PLAIN_MESSAGE,null,preferences.recentProjects.toArray(),preferences.recentProjects.get(0));if(recent!=null)openRecent(owner,recent);return;}boolean create="Create New Project".equals(choices[selected]);runWizard(owner,create);}
    static void runWizard(Component owner,boolean create){try{Path cache=chooseDirectory(owner,"Select the JS5 cache directory",null);if(cache==null)return;DesktopWorkflow.validateCache(cache);Path project=chooseProject(owner,create);if(project==null)return;Path export=chooseDirectory(owner,"Select an export folder",project.toAbsolutePath().getParent());if(export==null)return;int npc=72;if(create){String value=JOptionPane.showInputDialog(owner,"Initial NPC ID (you can browse NPCs after opening)","72");if(value==null)return;npc=Integer.parseInt(value.trim());}DesktopSession session=create?DesktopWorkflow.create(cache,project,export,npc):DesktopWorkflow.open(cache,project,export);openSession(owner,session);}catch(Exception e){showError(owner,e);}}
    static void openRecent(Component owner,DesktopPreferences.RecentProject recent){try{openSession(owner,DesktopWorkflow.open(Path.of(recent.cacheDirectory),Path.of(recent.projectFile),Path.of(recent.exportDirectory)));}catch(Exception e){showError(owner,e);}}
    static void openSession(Component owner,DesktopSession session){javax.swing.JDialog progress=new javax.swing.JDialog(SwingUtilities.getWindowAncestor(owner),"Opening project",java.awt.Dialog.ModalityType.APPLICATION_MODAL);javax.swing.JProgressBar bar=new javax.swing.JProgressBar();bar.setIndeterminate(true);bar.setStringPainted(true);bar.setString("Loading cache and NPC "+session.project.npcId+"…");progress.add(bar);progress.setSize(420,80);progress.setLocationRelativeTo(owner);javax.swing.SwingWorker<AnimationWorkspace,Void> worker=new javax.swing.SwingWorker<>(){protected AnimationWorkspace doInBackground()throws Exception{return new AnimationWorkspace(session.cacheDirectory,session.project.npcId);}protected void done(){progress.dispose();try{AnimationWorkspace workspace=get();AnimationDiscovery.populateKnown(session.project,workspace);remember(session);SelectorMain.SelectorFrame frame=new SelectorMain.SelectorFrame(workspace,session);frame.setVisible(true);if(owner instanceof java.awt.Window)((java.awt.Window)owner).dispose();}catch(Exception e){showError(owner,e);}}};worker.execute();progress.setVisible(true);}
    static void remember(DesktopSession session){try{DesktopPreferences p=DesktopPreferences.load(DesktopPreferences.defaultFile());p.remember(session);p.save(DesktopPreferences.defaultFile());}catch(Exception ignored){}}
    static Path chooseDirectory(Component owner,String title,Path initial){JFileChooser chooser=new JFileChooser(initial==null?null:initial.toFile());chooser.setDialogTitle(title);chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);return chooser.showOpenDialog(owner)==JFileChooser.APPROVE_OPTION?chooser.getSelectedFile().toPath():null;}
    static Path chooseProject(Component owner,boolean save){JFileChooser chooser=new JFileChooser();chooser.setDialogTitle(save?"Create Sprite Baker project":"Open Sprite Baker project");chooser.setFileFilter(new FileNameExtensionFilter("Sprite Baker project (*.json)","json"));int result=save?chooser.showSaveDialog(owner):chooser.showOpenDialog(owner);if(result!=JFileChooser.APPROVE_OPTION)return null;Path path=chooser.getSelectedFile().toPath();if(save&&!path.getFileName().toString().toLowerCase().endsWith(".json"))path=path.resolveSibling(path.getFileName()+".json");if(save&&Files.exists(path)&&JOptionPane.showConfirmDialog(owner,"Replace "+path+"?","Confirm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return null;return path;}
    static void showError(Component owner,Throwable error){Throwable cause=error;while(cause.getCause()!=null)cause=cause.getCause();JOptionPane.showMessageDialog(owner,cause.toString(),"RSC Sprite Baker",JOptionPane.ERROR_MESSAGE);}
}
