package com.spoiledmilk.spritebaker;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.AbstractAction;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JSpinner;
import javax.swing.JSplitPane;
import javax.swing.KeyStroke;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/** Swing animation-selection MVP; intentionally separate from the Phase-1 CLI entry point. */
public final class SelectorMain {
    private SelectorMain(){ }
    public static void main(String[] args)throws Exception{
        Arguments a=Arguments.parse(args);DesktopSession session=Files.exists(a.project)?DesktopWorkflow.open(a.cache,a.project,a.output):DesktopWorkflow.create(a.cache,a.project,a.output,a.npcId);
        AnimationWorkspace workspace=new AnimationWorkspace(session.cacheDirectory,session.project.npcId);int standing=session.project.standingSequenceId,walking=session.project.walkingSequenceId;AnimationDiscovery.populateKnown(session.project,workspace);session.dirty=standing!=session.project.standingSequenceId||walking!=session.project.walkingSequenceId;
        SwingUtilities.invokeLater(()->new SelectorFrame(workspace,session).setVisible(true));
    }

    static final class SelectorFrame extends JFrame {
        private final AnimationWorkspace workspace; private final DesktopSession session;private final SpriteProject project;
        private final StaticRenderer renderer=new StaticRenderer(); private final DefaultListModel<FrameChoice> timelineModel=new DefaultListModel<>();
        private final JList<FrameChoice> timeline=new JList<>(timelineModel); private final JSlider scrubber=new JSlider();
        private final JSpinner sequenceId=new JSpinner(new SpinnerNumberModel(0,0,65535,1)); private final JComboBox<String> role=new JComboBox<>(new String[]{"Standing","Walking","Combat","Other"});
        private final JComboBox<CombatCandidate> combatCandidates=new JComboBox<>();
        private final CellPanel[][] cellPanels=new CellPanel[3][6]; private PoseSelection selectedPose; private int selectedRow=0,selectedColumn=0; private Sequence530 loaded;
        private final JLabel actualPreview=new JLabel("Select a pose",JLabel.CENTER);
        private final JLabel materialStatus=new JLabel();
        private final JLabel status=new JLabel("Ready");private final JProgressBar progress=new JProgressBar();private int activeTasks;
        private long editVersion;
        private final DesktopTaskRunner tasks=new DesktopTaskRunner(new DesktopTaskRunner.Listener(){public void started(String label){activeTasks++;status.setText(label);progress.setIndeterminate(true);progress.setVisible(true);}public void finished(String label){activeTasks=Math.max(0,activeTasks-1);if(activeTasks==0){progress.setVisible(false);status.setText("Ready");}}});
        private JSpinner cellWidth,cellHeight,supersample,modelScale,pitch,yawOffset,vertical,ambient,diffuse,lightAzimuth,lightElevation,ditherStrength;
        private JComboBox<String> palette,dithering,preset; private boolean syncingControls;
        SelectorFrame(AnimationWorkspace workspace,DesktopSession session){
            super();this.workspace=workspace;this.session=session;this.project=session.project;this.editVersion=session.dirty?1:0;updateTitle();
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);addWindowListener(new java.awt.event.WindowAdapter(){public void windowClosing(java.awt.event.WindowEvent e){attemptClose();}public void windowClosed(java.awt.event.WindowEvent e){tasks.close();try{workspace.close();}catch(IOException ignored){}DesktopMain.editorClosed();}});setJMenuBar(menuBar());
            setLayout(new BorderLayout());JPanel north=new JPanel(new BorderLayout());north.add(visualPanel(),BorderLayout.CENTER);materialStatus.setText("Checking model and material compatibility…");materialStatus.setBorder(BorderFactory.createEmptyBorder(2,8,4,8));north.add(materialStatus,BorderLayout.SOUTH);add(north,BorderLayout.NORTH);JSplitPane split=new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,sourcePanel(),sheetPanel());split.setResizeWeight(.38);add(split,BorderLayout.CENTER);JPanel south=new JPanel(new BorderLayout());south.add(actions(),BorderLayout.NORTH);JPanel statusBar=new JPanel(new BorderLayout(8,0));statusBar.setBorder(BorderFactory.createEmptyBorder(3,8,3,8));statusBar.add(status,BorderLayout.CENTER);progress.setPreferredSize(new Dimension(220,18));progress.setVisible(false);statusBar.add(progress,BorderLayout.EAST);south.add(statusBar,BorderLayout.SOUTH);add(south,BorderLayout.SOUTH);
            setSize(1700,980);setLocationByPlatform(true);installShortcuts();sequenceId.setValue(Math.max(0,project.standingSequenceId));loadCompatibility();loadCombatCandidates();if(project.standingSequenceId>=0)loadSequence();
        }
        private void updateTitle(){String context=session.transientDesktop?"NPC "+project.npcId+" "+workspace.npc.name:session.projectFile.getFileName()+" — NPC "+project.npcId+" "+workspace.npc.name;setTitle((session.dirty?"* ":"")+"RSC Sprite Baker — "+context);}
        private JMenuBar menuBar(){JMenuBar bar=new JMenuBar();if(!session.transientDesktop){JMenu file=new JMenu("File");file.add(item("New Project…",()->{if(confirmLeave())DesktopMain.runWizard(this,true);}));file.add(item("Open Project…",()->{if(confirmLeave())DesktopMain.runWizard(this,false);}));JMenu recent=new JMenu("Open Recent");DesktopPreferences preferences=DesktopPreferences.load(DesktopPreferences.defaultFile());if(preferences.recentProjects.isEmpty())recent.setEnabled(false);for(DesktopPreferences.RecentProject entry:preferences.recentProjects)recent.add(item(entry.toString(),()->{if(confirmLeave())DesktopMain.openRecent(this,entry);}));file.add(recent);file.addSeparator();file.add(item("Save",this::save));file.add(item("Save As…",this::saveAs));file.add(item("Choose Export Folder…",this::chooseExport));file.addSeparator();file.add(item("Exit",this::attemptExit));bar.add(file);}JMenu npc=new JMenu("NPC");npc.add(item("Browse NPCs…",this::browseNpcs));npc.add(item("Compatibility Details",this::showDiagnostics));bar.add(npc);JMenu help=new JMenu("Help");help.add(item("About",()->JOptionPane.showMessageDialog(this,"RSC Sprite Baker\nBrowse an NPC, customize its sheet, and export PNG + provenance.\n\nDefault desktop work is temporary until exported.","About",JOptionPane.INFORMATION_MESSAGE)));bar.add(help);return bar;}
        private JMenuItem item(String label,Runnable action){JMenuItem item=new JMenuItem(label);item.addActionListener(e->action.run());return item;}
        private void save(){SpriteProject snapshot=project.copy();long version=editVersion;runAsync("Saving project…",()->{snapshot.save(session.projectFile);DesktopMain.remember(session);return session.projectFile;},path->{if(version==editVersion)session.dirty=false;updateTitle();status.setText("Saved "+path);});}
        private void saveAs(){Path selected=DesktopMain.chooseProject(this,true);if(selected==null)return;session.projectFile=selected;save();updateTitle();}
        private void chooseExport(){Path selected=DesktopMain.chooseDirectory(this,"Select export folder",session.exportDirectory);if(selected==null)return;session.exportDirectory=selected.toAbsolutePath().normalize();DesktopMain.remember(session);status.setText("Export folder: "+session.exportDirectory);}
        private void markDirty(){session.dirty=true;editVersion++;updateTitle();}
        private boolean confirmLeave(){if(!session.dirty)return true;if(session.transientDesktop){int choice=JOptionPane.showOptionDialog(this,"Adjustments for NPC "+project.npcId+" have not been exported.\nSwitching or closing will discard them.","Discard unexported adjustments?",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,new String[]{"Discard Adjustments","Keep Editing"},"Keep Editing");return choice==0;}int choice=JOptionPane.showConfirmDialog(this,"Save changes to "+session.projectFile.getFileName()+" before continuing?","Unsaved changes",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);if(choice==JOptionPane.CANCEL_OPTION||choice==JOptionPane.CLOSED_OPTION)return false;if(choice==JOptionPane.YES_OPTION)try{project.save(session.projectFile);session.dirty=false;DesktopMain.remember(session);updateTitle();}catch(Exception e){error(e);return false;}return true;}
        private void attemptClose(){if(confirmLeave())dispose();}
        private void attemptExit(){if(confirmLeave())DesktopMain.exitApplication();}
        private void browseNpcs(){new NpcBrowserDialog(this,session.cacheDirectory,entry->{if(!confirmLeave())return;try{DesktopSession next;if(session.transientDesktop)next=DesktopWorkflow.transientSession(session.cacheDirectory,session.exportDirectory,entry.id);else{Path selected=DesktopMain.chooseProject(this,true);if(selected==null)return;next=DesktopWorkflow.create(session.cacheDirectory,selected,session.exportDirectory,entry.id);}DesktopMain.openSession(this,next);}catch(Exception e){error(e);}}).setVisible(true);}
        private void showDiagnostics(){tasks.submit("Refreshing compatibility diagnostics…",()->TextureDiagnostics530.analyze(workspace.baseModel,workspace.npc,workspace.textures),report->JOptionPane.showMessageDialog(this,report.summary()+"\nMaterials: "+report.materialIds+"\nType-0 mappings: "+report.type0Mappings+"\nAdvanced face-local fallbacks: "+report.advancedMappingFallbacks+"\nErrors: "+report.errors,"NPC "+project.npcId+" compatibility",report.supported()?JOptionPane.INFORMATION_MESSAGE:JOptionPane.WARNING_MESSAGE),this::error);}
        private void loadCompatibility(){tasks.submit("Checking compatibility…",()->TextureDiagnostics530.analyze(workspace.baseModel,workspace.npc,workspace.textures),report->{materialStatus.setText(report.summary());materialStatus.setForeground(report.supported()?new Color(25,110,55):new Color(170,35,35));},this::error);}
        private void loadCombatCandidates(){combatCandidates.removeAllItems();tasks.submit("Finding likely combat animations…",()->AnimationDiscovery.combatCandidates(workspace),found->{for(CombatCandidate candidate:found)combatCandidates.addItem(candidate);combatCandidates.setToolTipText("Heuristic suggestions only; selecting one never assigns sheet cells automatically");},this::error);}
        private JPanel visualPanel(){JPanel panel=new JPanel(new GridLayout(2,8,4,2));VisualSettings v=project.visual;
            preset=new JComboBox<>(new String[]{"Unmodified studio","RSC crisp","RSC restrained","RSC coarse","Custom"});preset.setSelectedItem(v.preset);panel.add(labeled("Preset",preset));
            cellWidth=intSpinner(v.cellWidth,16,512,8);cellHeight=intSpinner(v.cellHeight,16,512,8);supersample=intSpinner(v.supersample,1,8,1);modelScale=doubleSpinner(v.modelScale,.25,4,.05);pitch=doubleSpinner(v.pitchDegrees,-45,60,1);yawOffset=doubleSpinner(v.yawOffsetDegrees,-45,45,1);vertical=doubleSpinner(v.verticalOffsetPixels,-128,128,1);
            ambient=doubleSpinner(v.ambient,0,1,.02);diffuse=doubleSpinner(v.diffuse,0,1,.02);lightAzimuth=doubleSpinner(v.lightAzimuthDegrees,-180,180,5);lightElevation=doubleSpinner(v.lightElevationDegrees,-90,90,5);ditherStrength=doubleSpinner(v.ditherStrength,0,1,.05);
            palette=new JComboBox<>(new String[]{PaletteReducer.UNMODIFIED,PaletteReducer.RSC_125,PaletteReducer.RSC_64,PaletteReducer.RSC_27});palette.setSelectedItem(v.palette);dithering=new JComboBox<>(new String[]{PaletteReducer.NO_DITHER,PaletteReducer.ORDERED_4X4});dithering.setSelectedItem(v.dithering);
            panel.add(labeled("Cell W",cellWidth));panel.add(labeled("H",cellHeight));panel.add(labeled("SS",supersample));panel.add(labeled("Scale",modelScale));panel.add(labeled("Pitch",pitch));panel.add(labeled("Yaw +",yawOffset));panel.add(labeled("Y +up",vertical));panel.add(labeled("Ambient",ambient));panel.add(labeled("Directional",diffuse));panel.add(labeled("Light az",lightAzimuth));panel.add(labeled("el",lightElevation));panel.add(labeled("Palette",palette));panel.add(labeled("Dither",dithering));panel.add(labeled("Strength",ditherStrength));
            java.util.List<JSpinner> spinners=java.util.List.of(cellWidth,cellHeight,supersample,modelScale,pitch,yawOffset,vertical,ambient,diffuse,lightAzimuth,lightElevation,ditherStrength);for(JSpinner spinner:spinners)spinner.addChangeListener(e->visualChanged());palette.addActionListener(e->visualChanged());dithering.addActionListener(e->visualChanged());preset.addActionListener(e->{if(!syncingControls&&!"Custom".equals(preset.getSelectedItem())){project.visual.applyPreset((String)preset.getSelectedItem());syncVisualControls();markDirty();refreshCells();}});return panel;}
        private static JPanel labeled(String text,JComponent component){JPanel p=new JPanel(new BorderLayout());p.add(new JLabel(text),BorderLayout.NORTH);p.add(component,BorderLayout.CENTER);return p;}
        private static JSpinner intSpinner(int value,int min,int max,int step){return new JSpinner(new SpinnerNumberModel(value,min,max,step));}
        private static JSpinner doubleSpinner(double value,double min,double max,double step){return new JSpinner(new SpinnerNumberModel(value,min,max,step));}
        private void syncVisualControls(){syncingControls=true;VisualSettings v=project.visual;cellWidth.setValue(v.cellWidth);cellHeight.setValue(v.cellHeight);supersample.setValue(v.supersample);modelScale.setValue(v.modelScale);pitch.setValue(v.pitchDegrees);yawOffset.setValue(v.yawOffsetDegrees);vertical.setValue(v.verticalOffsetPixels);ambient.setValue(v.ambient);diffuse.setValue(v.diffuse);lightAzimuth.setValue(v.lightAzimuthDegrees);lightElevation.setValue(v.lightElevationDegrees);palette.setSelectedItem(v.palette);dithering.setSelectedItem(v.dithering);ditherStrength.setValue(v.ditherStrength);syncingControls=false;}
        private void visualChanged(){if(syncingControls)return;VisualSettings v=project.visual;v.cellWidth=(Integer)cellWidth.getValue();v.cellHeight=(Integer)cellHeight.getValue();v.supersample=(Integer)supersample.getValue();v.modelScale=((Number)modelScale.getValue()).doubleValue();v.pitchDegrees=((Number)pitch.getValue()).doubleValue();v.yawOffsetDegrees=((Number)yawOffset.getValue()).doubleValue();v.verticalOffsetPixels=((Number)vertical.getValue()).doubleValue();v.ambient=((Number)ambient.getValue()).doubleValue();v.diffuse=((Number)diffuse.getValue()).doubleValue();v.lightAzimuthDegrees=((Number)lightAzimuth.getValue()).doubleValue();v.lightElevationDegrees=((Number)lightElevation.getValue()).doubleValue();v.palette=(String)palette.getSelectedItem();v.dithering=(String)dithering.getSelectedItem();v.ditherStrength=((Number)ditherStrength.getValue()).doubleValue();v.preset="Custom";syncingControls=true;preset.setSelectedItem("Custom");syncingControls=false;markDirty();refreshCells();}
        private JPanel sourcePanel(){
            JPanel panel=new JPanel(new BorderLayout());JPanel controls=new JPanel(new FlowLayout(FlowLayout.LEFT));controls.add(new JLabel("Source sequence"));controls.add(sequenceId);controls.add(role);JButton load=new JButton("Load timeline");load.addActionListener(e->loadSequence());controls.add(load);controls.add(new JLabel("Likely combat (review):"));combatCandidates.setPreferredSize(new Dimension(330,26));controls.add(combatCandidates);JButton useCandidate=new JButton("Preview candidate");useCandidate.addActionListener(e->{CombatCandidate candidate=(CombatCandidate)combatCandidates.getSelectedItem();if(candidate!=null){sequenceId.setValue(candidate.sequenceId);role.setSelectedItem("Combat");loadSequence();}});controls.add(useCandidate);panel.add(controls,BorderLayout.NORTH);
            timeline.setLayoutOrientation(JList.HORIZONTAL_WRAP);timeline.setVisibleRowCount(-1);timeline.setFixedCellWidth(112);timeline.setFixedCellHeight(142);
            timeline.setCellRenderer((list,value,index,isSelected,focus)->{JLabel label=new JLabel(value.toString(),value.icon,JLabel.CENTER);label.setHorizontalTextPosition(JLabel.CENTER);label.setVerticalTextPosition(JLabel.BOTTOM);label.setOpaque(true);label.setBackground(isSelected?new Color(255,220,150):list.getBackground());return label;});
            timeline.addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&timeline.getSelectedValue()!=null){scrubber.setValue((int)timeline.getSelectedValue().timeMillis);selectAt(scrubber.getValue());}});timeline.addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){if(e.getClickCount()==2)assignSelectedCell();}});
            panel.add(new JScrollPane(timeline),BorderLayout.CENTER);JPanel bottom=new JPanel();bottom.setLayout(new BoxLayout(bottom,BoxLayout.Y_AXIS));scrubber.addChangeListener(e->selectAt(scrubber.getValue()));bottom.add(new JLabel("Rendered timeline / 20 ms client-time scrubber"));bottom.add(scrubber);panel.add(bottom,BorderLayout.SOUTH);return panel;
        }
        private JPanel sheetPanel(){
            JPanel outer=new JPanel(new BorderLayout());JPanel grid=new JPanel(new GridLayout(4,7,4,4));grid.add(new JLabel("Pose / view"));for(String label:TargetSheet.COLUMN_LABELS)grid.add(new JLabel(label));
            for(int r=0;r<3;r++){grid.add(new JLabel(TargetSheet.ROW_LABELS[r]));for(int c=0;c<6;c++){CellPanel cp=new CellPanel(r,c);cellPanels[r][c]=cp;grid.add(cp);}}
            outer.add(grid,BorderLayout.CENTER);JPanel rowActions=new JPanel(new BorderLayout(8,0));actualPreview.setBorder(BorderFactory.createTitledBorder("Actual-size selected-cell preview"));rowActions.add(actualPreview,BorderLayout.WEST);JPanel commands=new JPanel(new GridLayout(0,1,3,3));
            for(int r=0;r<3;r++){final int row=r;JButton b=new JButton("Set "+TargetSheet.ROW_LABELS[r]+" row [Ctrl+"+(r+1)+"]");b.addActionListener(e->setSharedRow(row));commands.add(b);}
            JButton assign=new JButton("Replace selected cell [Enter]");assign.addActionListener(e->assignSelectedCell());commands.add(assign);
            JButton clear=new JButton("Use shared row pose");clear.addActionListener(e->{project.sheet.clearOverride(selectedRow,selectedColumn);markDirty();refreshCells();});commands.add(clear);rowActions.add(commands,BorderLayout.CENTER);outer.add(rowActions,BorderLayout.SOUTH);return outer;
        }
        private JPanel actions(){JPanel p=new JPanel(new FlowLayout(FlowLayout.RIGHT));JCheckBox mirror=new JCheckBox("Mirrored direction preview",project.mirroredPreview);mirror.addActionListener(e->{project.mirroredPreview=mirror.isSelected();markDirty();refreshCells();});p.add(mirror);
            JButton suggest=new JButton("Suggest empty cells");suggest.setToolTipText("Suggestions fill empty cells only and never replace selections");suggest.addActionListener(e->suggest());p.add(suggest);
            if(!session.transientDesktop){JButton save=new JButton("Save project");save.addActionListener(e->save());p.add(save);}
            JButton export=new JButton("Export PNG + provenance");export.addActionListener(e->exportSheet());p.add(export);return p;}
        private void exportSheet(){DesktopExportPlan plan=session.transientDesktop?DesktopExportPlan.forNpc(session.exportDirectory,project.npcId,workspace.npc.name):DesktopExportPlan.legacy(session.exportDirectory,project.npcId);if(plan.wouldOverwrite()&&JOptionPane.showConfirmDialog(this,"Existing output for this NPC will be replaced:\n"+plan.png+"\n"+plan.manifest,"Replace Existing Export?",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)!=JOptionPane.YES_OPTION)return;SpriteProject snapshot=project.copy();long version=editVersion;tasks.submit("Exporting 18-frame sheet…",()->{if(!session.transientDesktop)snapshot.save(session.projectFile);new SheetExporter().export(workspace,snapshot,plan);DesktopMain.remember(session);return plan;},result->{if(version==editVersion)session.dirty=false;updateTitle();JOptionPane.showMessageDialog(this,"Export complete.\n\nPNG:\n"+result.png+"\n\nProvenance:\n"+result.manifest,"Export Complete",JOptionPane.INFORMATION_MESSAGE);},this::error);}
        private void loadSequence(){int id=(Integer)sequenceId.getValue();String selected=(String)role.getSelectedItem();boolean changed=false;if("Standing".equals(selected)&&project.standingSequenceId!=id){project.standingSequenceId=id;changed=true;}else if("Walking".equals(selected)&&project.walkingSequenceId!=id){project.walkingSequenceId=id;changed=true;}else if("Combat".equals(selected)&&project.combatSequenceId!=id){project.combatSequenceId=id;changed=true;}if(changed)markDirty();VisualSettings visual=copy(project.visual);tasks.submit("Rendering sequence "+id+" timeline…",()->{Sequence530 sequence=workspace.cache.loadSequence(id);java.util.List<FrameChoice> frames=new java.util.ArrayList<>();for(int i=0;i<sequence.frameIds.length;i++){long time=AnimationTimeline.frameStartMillis(sequence,i);PoseSelection pose=new PoseSelection(AnimationTimeline.sample(sequence,time),"timeline");BufferedImage image=renderer.renderStyled(List.of(workspace.pose(pose,false)),workspace.npc,90,null,visual,workspace.textures);frames.add(new FrameChoice(i,time,icon(image,96,false)));}return new TimelineResult(sequence,frames);},result->{loaded=result.sequence;timelineModel.clear();for(FrameChoice frame:result.frames)timelineModel.addElement(frame);scrubber.setMaximum((int)Math.max(0,loaded.totalMillis()-1));scrubber.setValue(0);if(!timelineModel.isEmpty())timeline.setSelectedIndex(0);status.setText("Loaded sequence "+id+" — "+result.frames.size()+" frames");},this::error);}
        private void selectAt(long millis){if(loaded==null)return;selectedPose=new PoseSelection(AnimationTimeline.sample(loaded,millis),"timeline");refreshCells();}
        private void suggest(){int standing=project.standingSequenceId,walking=project.walkingSequenceId,combat=project.combatSequenceId;tasks.submit("Preparing pose suggestions…",()->{SuggestionSet out=new SuggestionSet();if(standing>=0){Sequence530 s=workspace.cache.loadSequence(standing);out.standing=new PoseSelection(AnimationTimeline.sample(s,0),"suggestion");}if(walking>=0){Sequence530 w=workspace.cache.loadSequence(walking);out.left=new PoseSelection(AnimationTimeline.sample(w,w.totalMillis()/3),"suggestion");out.right=new PoseSelection(AnimationTimeline.sample(w,w.totalMillis()*2/3),"suggestion");}if(combat>=0){Sequence530 a=workspace.cache.loadSequence(combat);out.combat=new PoseSelection[]{new PoseSelection(AnimationTimeline.sample(a,0),"suggestion"),new PoseSelection(AnimationTimeline.sample(a,a.totalMillis()/3),"suggestion"),new PoseSelection(AnimationTimeline.sample(a,a.totalMillis()*2/3),"suggestion")};}return out;},out->{boolean changed=false;if(out.standing!=null)for(int c=0;c<5;c++)changed|=project.sheet.suggest(0,c,out.standing);if(out.left!=null)for(int c=0;c<5;c++){changed|=project.sheet.suggest(1,c,out.left);changed|=project.sheet.suggest(2,c,out.right);}if(out.combat!=null)for(int r=0;r<3;r++)changed|=project.sheet.suggest(r,5,out.combat[r]);project.sheet.suggestCombatStandingFromSide();if(changed)markDirty();refreshCells();},this::error);}
        private void refreshCells(){if(cellPanels[0][0]==null)return;PoseSelection[][] poses=new PoseSelection[3][6];for(int r=0;r<3;r++)for(int c=0;c<6;c++)poses[r][c]=project.sheet.cells[r][c].pose==null?null:project.sheet.cells[r][c].pose.copy();PoseSelection actual=poses[selectedRow][selectedColumn]==null?(selectedPose==null?null:selectedPose.copy()):poses[selectedRow][selectedColumn];int actualColumn=selectedColumn;VisualSettings visual=copy(project.visual);boolean tween=project.tweening,mirror=project.mirroredPreview;tasks.submitLatest("Rendering previews…",()->renderBatch(poses,actual,actualColumn,visual,tween),batch->{for(int r=0;r<3;r++)for(int c=0;c<6;c++)cellPanels[r][c].apply(batch.images[r][c],batch.errors[r][c],mirror);if(batch.actual==null){actualPreview.setIcon(null);actualPreview.setText(actual==null?"Select a pose":"Unsupported: "+batch.actualError);}else{actualPreview.setText(null);actualPreview.setIcon(iconActual(batch.actual,mirror));}},this::error);}
        private RenderBatch renderBatch(PoseSelection[][] poses,PoseSelection actual,int actualColumn,VisualSettings visual,boolean tween)throws IOException{double[] yaw={0,45,90,135,180,90};java.util.List<StaticRenderer.View> views=new java.util.ArrayList<>();ModelDefinitionHolder[][] models=new ModelDefinitionHolder[3][6];RenderBatch batch=new RenderBatch();for(int r=0;r<3;r++)for(int c=0;c<6;c++)if(poses[r][c]!=null)try{net.runelite.cache.definitions.ModelDefinition model=workspace.pose(poses[r][c],tween);models[r][c]=new ModelDefinitionHolder(model);views.add(new StaticRenderer.View(model,yaw[c]));}catch(Exception e){models[r][c]=new ModelDefinitionHolder(e);}net.runelite.cache.definitions.ModelDefinition actualModel=null;if(actual!=null)try{actualModel=workspace.pose(actual,tween);if(views.isEmpty())views.add(new StaticRenderer.View(actualModel,yaw[actualColumn]));}catch(Exception e){batch.actualError=e.getMessage();}StaticRenderer.Viewport viewport=views.isEmpty()?null:renderer.fitStyled(views,workspace.npc,visual);for(int r=0;r<3;r++)for(int c=0;c<6;c++){ModelDefinitionHolder holder=models[r][c];if(holder==null)continue;if(holder.error!=null){batch.errors[r][c]=holder.error.getMessage();continue;}try{batch.images[r][c]=renderer.renderStyled(List.of(holder.model),workspace.npc,yaw[c],viewport,visual,workspace.textures);}catch(Exception e){batch.errors[r][c]=e.getMessage();}}if(actualModel!=null)try{batch.actual=renderer.renderStyled(List.of(actualModel),workspace.npc,yaw[actualColumn],viewport,visual,workspace.textures);}catch(Exception e){batch.actualError=e.getMessage();}return batch;}
        private void assignSelectedCell(){if(selectedPose!=null){project.sheet.override(selectedRow,selectedColumn,selectedPose);markDirty();refreshCells();}}
        private void setSharedRow(int row){if(selectedPose!=null){project.sheet.assignShared(row,selectedPose);project.sheet.suggestCombatStandingFromSide();markDirty();refreshCells();}}
        private void installShortcuts(){bind("ENTER","assign",this::assignSelectedCell);bind("ctrl 1","row0",()->setSharedRow(0));bind("ctrl 2","row1",()->setSharedRow(1));bind("ctrl 3","row2",()->setSharedRow(2));bind("L","lock",()->{TargetSheet.Cell cell=project.sheet.cells[selectedRow][selectedColumn];cell.locked=!cell.locked;markDirty();refreshCells();});bind("BACK_SPACE","shared",()->{project.sheet.clearOverride(selectedRow,selectedColumn);markDirty();refreshCells();});}
        private void bind(String stroke,String name,Runnable action){getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(stroke),name);getRootPane().getActionMap().put(name,new AbstractAction(){public void actionPerformed(java.awt.event.ActionEvent e){action.run();}});}
        private final class CellPanel extends JPanel {final int row,col;final JLabel preview=new JLabel("Empty",JLabel.CENTER);final JCheckBox lock=new JCheckBox("Lock");CellPanel(int row,int col){this.row=row;this.col=col;setLayout(new BorderLayout());setPreferredSize(new Dimension(135,190));add(preview,BorderLayout.CENTER);add(lock,BorderLayout.SOUTH);lock.addActionListener(e->{project.sheet.cells[row][col].locked=lock.isSelected();markDirty();});MouseAdapter select=new MouseAdapter(){public void mouseClicked(MouseEvent e){selectedRow=row;selectedColumn=col;if(e.getClickCount()==2)assignSelectedCell();else refreshCells();}};addMouseListener(select);preview.addMouseListener(select);apply(null,null,false);}
            void apply(BufferedImage image,String error,boolean mirror){TargetSheet.Cell cell=project.sheet.cells[row][col];lock.setSelected(cell.locked);Color state=cell.locked?new Color(180,55,55):cell.override?new Color(50,110,200):cell.pose!=null&&"suggestion".equals(cell.pose.source)?new Color(150,75,180):cell.pose!=null?new Color(50,145,85):Color.GRAY;javax.swing.border.Border stateBorder=BorderFactory.createTitledBorder(BorderFactory.createLineBorder(state,2),cell.pose==null?"Empty":cell.locked?"LOCKED":cell.override?"OVERRIDE":"suggestion".equals(cell.pose.source)?"SUGGESTION":"SHARED");setBorder(row==selectedRow&&col==selectedColumn?BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.ORANGE,3),stateBorder):stateBorder);if(cell.pose==null){preview.setIcon(null);preview.setText("Double-click to assign");return;}if(error!=null){preview.setIcon(null);preview.setText("UNSUPPORTED: "+error);setToolTipText(error);return;}if(image==null){preview.setIcon(null);preview.setText("Rendering…");return;}preview.setIcon(icon(image,112,mirror));preview.setText("S"+cell.pose.sequenceId+" F"+cell.pose.frameIndex+" +"+cell.pose.cycleOffset);preview.setHorizontalTextPosition(JLabel.CENTER);preview.setVerticalTextPosition(JLabel.BOTTOM);setToolTipText(cell.pose.source+"; "+(cell.locked?"locked":"editable"));}
        }
        private <T> void runAsync(String label,DesktopTaskRunner.Task<T> action,java.util.function.Consumer<T> success){tasks.submit(label,action,success,this::error);}
        private void error(Exception e){status.setText("Error: "+root(e));JOptionPane.showMessageDialog(this,root(e),"Error",JOptionPane.ERROR_MESSAGE);}
        private static String root(Throwable e){while(e.getCause()!=null)e=e.getCause();return e.toString();}
        private static VisualSettings copy(VisualSettings source){VisualSettings out=new VisualSettings();out.cellWidth=source.cellWidth;out.cellHeight=source.cellHeight;out.supersample=source.supersample;out.padding=source.padding;out.modelScale=source.modelScale;out.pitchDegrees=source.pitchDegrees;out.yawOffsetDegrees=source.yawOffsetDegrees;out.verticalOffsetPixels=source.verticalOffsetPixels;out.ambient=source.ambient;out.diffuse=source.diffuse;out.lightAzimuthDegrees=source.lightAzimuthDegrees;out.lightElevationDegrees=source.lightElevationDegrees;out.palette=source.palette;out.dithering=source.dithering;out.ditherStrength=source.ditherStrength;out.preset=source.preset;return out;}
    }
    private static final class TimelineResult{final Sequence530 sequence;final java.util.List<FrameChoice> frames;TimelineResult(Sequence530 sequence,java.util.List<FrameChoice> frames){this.sequence=sequence;this.frames=frames;}}
    private static final class SuggestionSet{PoseSelection standing,left,right;PoseSelection[] combat;}
    private static final class ModelDefinitionHolder{net.runelite.cache.definitions.ModelDefinition model;Exception error;ModelDefinitionHolder(net.runelite.cache.definitions.ModelDefinition model){this.model=model;}ModelDefinitionHolder(Exception error){this.error=error;}}
    private static final class RenderBatch{final BufferedImage[][] images=new BufferedImage[3][6];final String[][] errors=new String[3][6];BufferedImage actual;String actualError;}
    private static final class FrameChoice {final int index;final long timeMillis;final ImageIcon icon;FrameChoice(int i,long t,ImageIcon icon){index=i;timeMillis=t;this.icon=icon;}public String toString(){return "Frame "+index+" @ "+timeMillis+" ms";}}
    private static ImageIcon icon(BufferedImage source,int size,boolean mirror){BufferedImage transformed=new BufferedImage(source.getWidth(),source.getHeight(),BufferedImage.TYPE_INT_ARGB);Graphics2D g=transformed.createGraphics();if(mirror)g.drawImage(source,source.getWidth(),0,-source.getWidth(),source.getHeight(),null);else g.drawImage(source,0,0,null);g.dispose();Image scaled=transformed.getScaledInstance(size,size,Image.SCALE_SMOOTH);return new ImageIcon(scaled);}
    private static ImageIcon iconActual(BufferedImage source,boolean mirror){if(!mirror)return new ImageIcon(source);BufferedImage transformed=new BufferedImage(source.getWidth(),source.getHeight(),BufferedImage.TYPE_INT_ARGB);Graphics2D g=transformed.createGraphics();g.drawImage(source,source.getWidth(),0,-source.getWidth(),source.getHeight(),null);g.dispose();return new ImageIcon(transformed);}
    private static final class Arguments{Path cache,project,output;int npcId=72;static Arguments parse(String[] args){Arguments a=new Arguments();for(int i=0;i<args.length;i+=2){if(i+1>=args.length)usage();switch(args[i]){case"--cache":a.cache=Path.of(args[i+1]);break;case"--project":a.project=Path.of(args[i+1]);break;case"--output-dir":a.output=Path.of(args[i+1]);break;case"--npc":a.npcId=Integer.parseInt(args[i+1]);break;default:usage();}}if(a.cache==null||a.project==null||a.output==null)usage();return a;}static void usage(){throw new IllegalArgumentException("usage: --cache PATH --project FILE --output-dir PATH [--npc ID]");}}
}
